- hosts: bolt_microservice
  name: start all bolt_microservice
  vars_files: vars/all.yml
  tasks:
    - name: Install packages based on package.json.
      npm:
        path: "{{ item }}"
      with_items:
        # - "contracts"
        # - "gringotts"
        - "BOLT-KEYSTONE"
        - "BOLT-KEYCHAIN"
        - "BOLT-TRUST"
        - "BOLT-CURRENCY"
    - name: cp env file & deploy script
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
    #     - { src: ./script/deployContract.sh, dest: "contracts/deployContract.sh" } 
    #     - { src: ./env/contracts/env.js, dest: "contracts/env.js" } 
    #     - { src: ./env/BOLT-CURRENCY/env.js, dest: "BOLT-CURRENCY/env.js" } 
    #     - { src: ./env/BOLT-KEYCHAIN/env.js, dest: "BOLT-KEYCHAIN/env.js" } 
        - { src: ./env/BOLT-KEYSTONE/env, dest: "BOLT-KEYSTONE/env" } 
    #     - { src: ./env/BOLT-TRUST/env.js, dest: "BOLT-TRUST/env.js" }
    # - name: generation the gringotts env
    #   template:
    #     src: env/gringotts/env.js.j2
    #     dest: gringotts/env.js
    # - name: truffle deploy
    #   command: sh deployContract.sh
    #   args:
    #     chdir: "contracts"
    - name: migrate gringotts
      shell: NODE_ENV=production ./node_modules/.bin/sequelize db:migrate --config env.js --migrations-path ./storage-manager/migrations --models-path ./storage-manager/models
      ignore_errors: true
      args:
        chdir: "gringotts"
    - name: start gringotts
      shell: rm -rf ./chaindata/level ./chaindata/rocksdb ./db; /usr/local/lib/npm/bin/pm2 start server.js -n gringotts
      ignore_errors: true
      args:
        chdir: "gringotts"
    - name: generation the BOLT-CURRENCY env
      template:
        src: env/BOLT-CURRENCY/env.js.j2
        dest: BOLT-CURRENCY/env.js
    - name: start migrate
      command: /usr/local/lib/npm/bin/pm2 start . -n BOLT-CURRENCY
      ignore_errors: true
      args:
        chdir: "BOLT-CURRENCY"
    - name: generation the BOLT-KEYCHAIN env
      template:
        src: env/BOLT-KEYCHAIN/env.js.j2
        dest: BOLT-KEYCHAIN/env.js
    - name: start BOLT-KEYCHAIN
      command: /usr/local/lib/npm/bin/pm2 start . -n BOLT-KEYCHAIN
      ignore_errors: true
      args:
        chdir: "BOLT-KEYCHAIN"
    - name: start BOLT-KEYSTONE
      command: /usr/local/lib/npm/bin/pm2 start . -n BOLT-KEYSTONE
      ignore_errors: true
      args:
        chdir: "BOLT-KEYSTONE"
    - name: generation the BOLT-TRUST env
      template:
        src: env/BOLT-TRUST/env.js.j2
        dest: BOLT-TRUST/env.js
    - name: migrate BOLT-TRUST
      shell: NODE_ENV=development ./node_modules/.bin/sequelize db:migrate --config env.js --migrations-path ./src/database/migrations --models-path ./src/database/models
      ignore_errors: true
      args:
        chdir: "BOLT-TRUST"
    - name: start BOLT-TRUST
      command: /usr/local/lib/npm/bin/pm2 start . -n BOLT-TRUST
      ignore_errors: true
      args:
        chdir: "BOLT-TRUST"
  environment:
    - LC_CTYPE: en_US.UTF-8
    - LC_ALL: en_US.UTF-8

- hosts: bolt_microservice
  name: register all service user
  vars_files: vars/all.yml
  tasks:
    - name: call keystone to register authModule
      uri:
        url: "http://{{ bolt_microservice_ip }}:5999/register"
        method: POST
        body: {"userID": "authModule", "password": "{{ authModulePassword }}", "profile": { "name": "authModule", "phone": "0987654321" }}
        body_format: json
        headers:
          Content-Type: "application/json"
        return_content: yes
    - name: call keystone to register opAccount
      uri:
        url: "http://{{ bolt_microservice_ip }}:5999/register"
        method: POST
        body: {"userID": "opAccount", "password": "{{ opAccountPassword }}", "profile": { "name": "opAccount", "phone": "0987654321" }}
        body_format: json
        headers:
          Content-Type: "application/json"
        return_content: yes
    - name: call keystone to register receptionDesk
      uri:
        url: "http://{{ bolt_microservice_ip }}:5999/register"
        method: POST
        body: {"userID": "receptionDesk", "password": "{{ receptionDeskPassword }}", "profile": { "name": "receptionDesk", "phone": "0987654321" }}
        body_format: json
        headers:
          Content-Type: "application/json"
        return_content: yes
      register: registerReceptionDesk
    - name: call keystone to register fundManagement
      uri:
        url: "http://{{ bolt_microservice_ip }}:5999/register"
        method: POST
        body: {"userID": "fundManagement", "password": "{{ fundManagementPassword }}", "profile": { "name": "fundManagement", "phone": "0987654321" }}
        body_format: json
        headers:
          Content-Type: "application/json"
        return_content: yes
      register: registerFundManagement

- hosts: bolt_main
  name: set microservice env and start service
  vars_files: vars/all.yml
  tasks:
    - name: Install packages based on package.json.
      npm:
        path: "{{ item }}"
      with_items:
        - "Howinvest-APIGateway"
        - "BOLT-AUTOMATION"
    - name: cp env file & deploy script
      copy:
        src: "./env/Howinvest-APIGateway/private"
        dest: "Howinvest-APIGateway"
    - name: generation the BOLT-AUTOMATION env
      template:
        src: env/BOLT-AUTOMATION/env.js.j2
        dest: BOLT-AUTOMATION/config/env.js
    - name: generation the HowinvestMockAPI config
      template:
        src: env/Howinvest-APIGateway/private/config.toml.j2
        dest: Howinvest-APIGateway/private/config.toml
    - name: set cap can net bind service
      become: yes
      command: setcap cap_net_bind_service=+ep /usr/bin/node
    - name: start Howinvest-APIGateway
      command: /usr/local/lib/npm/bin/pm2 start . -n Howinvest-APIGateway
      ignore_errors: true
      args:
        chdir: "Howinvest-APIGateway"

- hosts: howinvest_microservice
  name: set microservice env and start service
  vars_files: vars/all.yml
  tasks:
    - name: Install packages based on package.json.
      npm:
        path: "{{ item }}"
      with_items:
        - "HowInvest-AuthModule"
        - "HowInvest-TradeModule"
        - "HowInvest-Blacklist"
    - name: cp env file
      copy:
        src: "./env/HowInvest-AuthModule/private"
        dest: "HowInvest-AuthModule"
    - name: cp env file
      copy:
        src: "./env/HowInvest-TradeModule/private"
        dest: "HowInvest-TradeModule"
    - name: cp env file
      copy:
        src: "./env/HowInvest-Blacklist/private"
        dest: "HowInvest-Blacklist"
    - name: generation the HowInvest-AuthModule config
      template:
        src:  ./env/HowInvest-AuthModule/private/config.toml.j2
        dest: HowInvest-AuthModule/private/config.toml
    - name: generation the HowInvest-TradeModule config
      template:
        src:  ./env/HowInvest-TradeModule/private/config.toml.j2
        dest: HowInvest-TradeModule/private/config.toml
    - name: generation the HowInvest-Blacklist config
      template:
        src:  ./env/HowInvest-Blacklist/private/config.toml.j2
        dest: HowInvest-Blacklist/private/config.toml
    - name: set AuthModule config
      shell: 
        sed -i "s#fundManagementAddress#{{ hostvars['bolt_microservice']['registerFundManagement'].json.profile.address }}#g" HowInvest-AuthModule/private/config.toml;
        sed -i "s#receptionDeskAddress#{{ hostvars['bolt_microservice']['registerReceptionDesk'].json.profile.address }}#g" HowInvest-AuthModule/private/config.toml;
      ignore_errors: true
    - name: start HowInvest-AuthModule
      command: /usr/local/lib/npm/bin/pm2 start . -n HowInvest-AuthModule
      ignore_errors: true
      args:
        chdir: "HowInvest-AuthModule"
    - name: start HowInvest-TradeModule
      command: /usr/local/lib/npm/bin/pm2 start . -n HowInvest-TradeModule
      ignore_errors: true
      args:
        chdir: "HowInvest-TradeModule"
    - name: start HowInvest-Blacklist
      command: /usr/local/lib/npm/bin/pm2 start . -n HowInvest-Blacklist
      ignore_errors: true
      args:
        chdir: "HowInvest-Blacklist"

- hosts: multi
  sudo: yes
  vars_files: vars/all.yml
  tasks:
    - name: Change ~/.ssh, group and permissions
      file:
        path: "/home/{{ agent_user }}/.ssh"
        owner: "{{ agent_user }}"
        group: "{{ agent_user }}"